name: Test NixOS distro

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-nixos-and-run-hello:
    runs-on: ubuntu-latest
    container:
      image: asterinas/asterinas:0.16.1-20250922
      options: --device=/dev/kvm --privileged -v /dev:/dev
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Install essential tools
        run: |
          apt update && apt install parted dosfstools -y
          nix-env -iA nixpkgs.nixos-install-tools
      - name: Build NixOS image and run hello
        run: |
          make run NIXOS=1 NIXOS_DISK_SIZE_IN_MB=4096 NIXOS_STAGE_2_ARGS=hello-asterinas || true
          tail --lines 10 qemu.log | grep -q "^Hello Asterinas!" || (echo "Test NixOS failed" && exit 1)
          make clean
          echo "Test NixOS succeeds!"