name: "Test x86-64  "

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest
    container:
      image: asterinas/asterinas:0.17.0-20260114
      options: --device=/dev/kvm --privileged
      volumes:
        # Map the following directories on the host into the container so that
        # the container can remove them to save some precious disk space (~16GB),
        # which is quite limited on free-tier Github runners.
        - /usr/lib/google-cloud-sdk:/usr/lib/google-cloud-sdk
        - /usr/local/lib/android:/usr/local/lib/android
        - /usr/share/dotnet:/usr/share/dotnet
    strategy:
      matrix:
        include:
          # Syscall Test at Ext2 (MicroVM)
          - test_id: 'syscall-ext2-microvm'
            scheme: 'microvm'
            extra_blocklists: 'blocklists.ext2'
            syscall_test_workdir: '/ext2'
      fail-fast: false
    steps:
      - name: Free disk space
        # Remove unused packages from the host to save disk space.
        run: rm -rf /usr/lib/google-cloud-sdk/* /usr/local/lib/android/* /usr/share/dotnet/*
      - uses: actions/checkout@v4
      - name: Run integration tests ${{ (startsWith(matrix.test_id, 'syscall') && 'with LTP') || '' }}
        uses: ./.github/actions/test
        with:
          auto_test: ${{ (startsWith(matrix.test_id, 'boot') && 'boot') ||
              (startsWith(matrix.test_id, 'syscall') && 'syscall') || 'test' }}
          release: ${{ !contains(matrix.release, 'false') }}
          enable_kvm: ${{ !contains(matrix.enable_kvm, 'false') }}
          smp: ${{ matrix.smp }}
          netdev: ${{ matrix.netdev || 'tap' }}
          scheme: ${{ matrix.scheme }}
          extra_blocklists: ${{ matrix.extra_blocklists }}
          syscall_test_suite: 'ltp'
          syscall_test_workdir: ${{ matrix.syscall_test_workdir }}
          boot_protocol: ${{ matrix.boot_protocol || 'linux-efi-handover64' }}
      - name: Run integration tests ${{ (startsWith(matrix.test_id, 'syscall') && 'with gVisor') || '' }}
        if: ${{ startsWith(matrix.test_id, 'syscall') }}
        uses: ./.github/actions/test
        with:
          auto_test: ${{ (startsWith(matrix.test_id, 'boot') && 'boot') ||
              (startsWith(matrix.test_id, 'syscall') && 'syscall') || 'test' }}
          release: ${{ !contains(matrix.release, 'false') }}
          enable_kvm: ${{ !contains(matrix.enable_kvm, 'false') }}
          smp: ${{ matrix.smp }}
          netdev: ${{ matrix.netdev || 'tap' }}
          scheme: ${{ matrix.scheme }}
          extra_blocklists: ${{ matrix.extra_blocklists }}
          syscall_test_suite: 'gvisor'
          syscall_test_workdir: ${{ matrix.syscall_test_workdir }}
          boot_protocol: ${{ matrix.boot_protocol || 'linux-efi-handover64' }}

